# Site settings
name: Less Or More
email: liucui_2008@163.com
author: Fantaishao
url: ''
resume_site: ''
github: https://github.com/fantaishao/
baseurl: "/fantaishao.github.io"
description: Actually, less is more!
meta_description: Fantaishao;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 不忘初心，方得始终.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:categories/:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: fantaishao

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

